version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "289857919920"
    REPOSITORY_NAME: "vishu-website"
    CONTAINER_NAME: "vishu-website"
    CLUSTER_NAME: "websitecluster"
    AWS_DEFAULT_REGION: "ap-south-1"
    IMAGE_TAG: "latest"
phases:
  pre_build:
  commands:
    - mkdir -p ~/.docker
    - echo '{"credsStore":""}' > ~/.docker/config.json
    - aws ecr get-login-password ... (your login command)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
artifacts:
  files: imagedefinitions.json
